### ISSUE TITLE
TypeError: $ is undefined

### ISSUE THREAD

**Issue by virgo79** [ipsips/acf-audio-video#1]
Hi,
I'm tring to use this plugin toghether with ACF 5 pro and latest version of wordpress (actually 4.6.1).

I've created and added the field to an acf field group.
But, while in the post edit screen, when I click the Add Audio/video Button nothing happens and the following js error is thrown

`TypeError: $ is undefined` on acf-audio-video-field.min.js line 413

The error is related to the `$.isNumeric()` call.

P.S. there is even a php warning that appears in the debug.log wordpress file:
`PHP Notice:  Undefined variable: tag in /home/.../public_html/wp-content/plugins/acf-audio-video-1.0.0/acf-audio-video-field.php on line 220`

Hope it can helps and that you could fix them.
Thanks for creating and sharing this plugin I was searching for it from many time.

**Comment by ipsips** [comment]
Hey @virgo79, sorry for the late response. I did some fixes and these things should be resolved now. Let me know if you encounter any further problems.

**Comment by virgo79** [comment]
Hi ipsips,

thanks for your reply and for fixing the problem.
I'm trying the field and now seems to work very well. I can't realize why this type of fields are not integrated into acf pro official.

Anyway, I wish to report the following php warning:

`PHP Warning:  array_filter() expects parameter 1 to be array, string given in /home/.../public_html/wp-content/plugins/acf-audio-video-1.0.0/acf-audio-video-field.php on line 270`

that  probably come out when you insert only one extension file in the 'Allowed file types' field attribute.

Thank you very much again.
