### ISSUE TITLE
Allowed file type setting does not work (and a quick suggestion for fix this)

### ISSUE THREAD

**Issue by virgo79** [ipsips/acf-audio-video#2]
Hi @ipsips,

I've inserted one or more extension files (e.g. "mp4,mp3") into the "Allowed file type" field setting, but in the edit post screen file restrictions does not happens, and a php warning is thrown in the debug log file.

The problem is inside the function `_get_allowed_types` of the `acf-audio-video-field.php` .

The array_filter function at line 261 takes as first param an array, but, actually, a string is given.

To fix this I've changed line 262 `explode(',', $field['allowed_types'] )`
and line 273 with `implode(',', $valid_allowed_types)`, to return back values as string.

This has been tested and seems to works fine.

**Comment by ipsips** [comment]
Hey, another good catch, @virgo79. Needed to add exactly what you suggested.

Now the upload frame should complain "Sorry, you cannot upload this file type for this field." if you try to upload a file with a non-allowed extension and any previously uploaded files that don't fit the criteria are not displayed as selectable either.

Reopen this issue if you still encounter problems regarding allowed types and thanks!

**Comment by virgo79** [comment]
Hi @ipsips, thanks for the fix.

I think the code need another bit of fixing.

The allowed mime types restrictions works correctly only if you have "both" option selected in "Type" Setting of the field. If you swap to "video" or "audio" option the following warning happens and the "mime types allowed" fallsback to the general video or general audio mime types.

PHP Notice:  Undefined variable: field in /home/.../public_html/wp-content/plugins/fields-audio-video/acf-audio-video-field.php on line 267
PHP Notice:  Undefined index:  in /home/.../public_html/wp-content/plugins/fields-audio-video/acf-audio-video-field.php on line 267
