### ISSUE TITLE
Field not properly saved when created inside a flexible content field

### ISSUE THREAD

**Issue by virgo79** [ipsips/acf-audio-video#3]
Hi @ipsips,

there is a saving issue when the field is added to a flexible content field.
With the flexible content field (that is built-in in acf pro 5) you can create multiple layouts that groups toghether different acf fields.
When adding the acf audio/video field into a flexible content field, the field value is not properly saved.
Taking a look into the database seems that the field is stored as separate value, and not as a flexible content value.

Following theese steps you can reproduce the error:

1. Create a flexible content field
2. Create a layout (e.g. multimedia) inside a flexible content field.
3. add the acf audio/video field into this layout
4. save
5. go to the edit post screen
6. add a multimedia layout and select a video or audio file
7. save
8 the page reload and the field lost the selected file, appearing empty.

**Comment by ipsips** [comment]
Had to tweak the javascript to play nice with other layout fields besides the repeater. should be ok now.
